// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCM3JRi76m71fisedK8VSq11HY97z-4Tb0',
    appId: '1:991569424055:web:d2d12cb60b5668cd3f2732',
    messagingSenderId: '991569424055',
    projectId: 'book-store-a18bc',
    authDomain: 'book-store-a18bc.firebaseapp.com',
    storageBucket: 'book-store-a18bc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0TKquAcpM4REWu6Fhzya9VtQGvV48wgo',
    appId: '1:991569424055:android:34c2cff1905785353f2732',
    messagingSenderId: '991569424055',
    projectId: 'book-store-a18bc',
    storageBucket: 'book-store-a18bc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCrYMeFEnpGcCMsjiVBDb68lkjD_1E9LCI',
    appId: '1:991569424055:ios:bc101c50382cec0d3f2732',
    messagingSenderId: '991569424055',
    projectId: 'book-store-a18bc',
    storageBucket: 'book-store-a18bc.appspot.com',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCrYMeFEnpGcCMsjiVBDb68lkjD_1E9LCI',
    appId: '1:991569424055:ios:bc101c50382cec0d3f2732',
    messagingSenderId: '991569424055',
    projectId: 'book-store-a18bc',
    storageBucket: 'book-store-a18bc.appspot.com',
    iosBundleId: 'com.example.bookStore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCM3JRi76m71fisedK8VSq11HY97z-4Tb0',
    appId: '1:991569424055:web:a348bbdda50f4ccd3f2732',
    messagingSenderId: '991569424055',
    projectId: 'book-store-a18bc',
    authDomain: 'book-store-a18bc.firebaseapp.com',
    storageBucket: 'book-store-a18bc.appspot.com',
  );
}
